<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{f2c55725-7b8a-4083-abeb-dc6829ffb8f1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nCounter : INT := 10_000; 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>